name: Docker Build and Push image

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry scorpio2002/shellcheck
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: scorpio2002/shellcheck
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}